name: Authenticate with GitHub
description: Authenticate with GitHub using the gh CLI.

inputs:  
  USER_PAT:
    description: 'Enter the user PAT'
    required: true 
  HOST_NAME:
    description: 'Enter the hostname'
    required: true  

runs:
  using: composite
  steps:
      - name: Authenticate with GitHub GHEC
        run: echo "${{ inputs.USER_PAT  }}" | gh auth login --with-token
        shell: bash  
      # - name: Authenticate with GitHub
      #   run: echo "${{ inputs.USER_PAT  }}" | gh auth login -h "${{ inputs.HOST_NAME }}" --with-token
      #   shell: bash  
