name: process-provision-issue

on:
  workflow_dispatch

permissions:
  contents: read
  issues: write

defaults:
  run:
    shell: bash

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  execute-issue-to-pr:
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.prepare.outputs.command }}
      log-filename: ${{ steps.logs.outputs.filename }}
    steps:
      - name: Update Provisioner Issue
        id: update-provisioner-issue
        uses: actions/github-script@v6

        if: always()
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['create-provisioner-pullrequest-running']
            })
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare arguments
        id: prepare
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          LABELS: ${{ toJSON(github.event.issue.labels.*.name) }}
        run: |
          ./bin/parse_issue "$ISSUE_BODY" "$COMMENT_BODY" "$LABELS"
      - name: Validate arguments
        run: |
          if [ -z "${{ steps.prepare.outputs.provider }}" ]; then
            echo "Unable to determine provider"
            exit 1
          elif [ -z "${{ steps.prepare.outputs.command }}" ]; then
            echo "Unable to determine command"
            exit 1
          fi
      - name: execute create-provisioner-pullrequest
        uses: ./provisioner/actions/create-pullrequest

