name: Update the logs to README.md file
description: Update the README.md file with the latest logs
inputs:
  REQUESTOR:
    description: Enter Requestor name
    required: true    
  CREATED_AT:
    description: Enter the CREATED_AT date
    required: true
  ISSUE_URL:
    description: Enter the ISSUE_URL
    required: true
  ISSUE_ASSIGNEES:
    description: Enter the ASSIGNEES
    required: true
  ISSUE_JSON:
    description: Enter the ISSUE_JSON
    required: true
  BRANCH_NAME:
    description: Enter the BRANCH_NAME
    required: true  
  GITHUB_TOKEN:
    description: Enter the GITHUB_TOKEN
    required: true

runs:
  using: composite
  steps:
    
    - name: Checkout the repository
      run: |
        git checkout ${{ inputs.BRANCH_NAME }}  
    
        #Check if the file exists in the destination directory
        if [ ! -f $GITHUB_WORKSPACE/provisioner/README.md ]; then
          echo "File does not exists in root directory"
          #Create the README.md file and add the table headers
          echo "| Requestor | Date | Issue URL | Issue Assignees | Issue JSON | New or Update |" >> $GITHUB_WORKSPACE/provisioner/README.md
          echo "| --- | --- | --- | --- | --- | --- |" >> $GITHUB_WORKSPACE/provisioner/README.md
        fi
          echo "File exist in root directory"
          echo "| ${{ inputs.REQUESTOR }} | ${{ inputs.CREATED_AT }} | ${{ inputs.ISSUE_URL }} | ${{ inputs.ISSUE_ASSIGNEES }} | ${{ env.ISSUE_JSON }} | ${{ fromJson(env.ISSUE_JSON).create-modify-repo }} | " >> $GITHUB_WORKSPACE/provisioner/README.md
      
      env:
       ISSUE_JSON: ${{ inputs.ISSUE_JSON }} 
       GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash 
