name: Update Repository
description: Updates a repository within an organization using the gh CLI.

inputs:
  ORG_NAME:
    description: 'Enter organization name'
    required: true
  REPO_NAME:
    description: 'Enter name of repository'
    required: true  
  HOME_PAGE:
    description: 'Enter the homepage'
    default: 'https://im-kp-es379.eastus.cloudapp.azure.com'
  DESCRIPTION: 
    description: 'Enter the description'
    default: 'This is a test repository'    
  PRIVATE:
    description: 'Mention whether repository is private or not'
    default: 'true'
  HAS_ISSUES:
    description: 'Mention whether repository can have issues or not'
    default: 'true'
  HAS_PROJECTS:
    description: 'Mention whether repository can have projects or not'
    default: 'true'
  HAS_WIKI:
    description: 'Mention whether repository can have wiki or not'
    default: 'true'  
  HAS_DISCUSSIONS:
    description: 'Mention whether repository can have discussions or not'
    default: 'true'

runs:
  using: composite
  steps:    

    - name: update repository
      run: |    

        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.ORG_NAME }}/${{ inputs.REPO_NAME }} \
          -f name='${{ inputs.REPO_NAME }}' \
        -f description='${{ inputs.DESCRIPTION }}' \
        -f homepage='${{ inputs.HOME_PAGE }}' \
        -F private=${{ inputs.PRIVATE }} \
        -F has_issues=${{ inputs.HAS_ISSUES }} \
        -F has_projects=${{ inputs.HAS_PROJECTS }} \
        -F has_wiki=${{ inputs.HAS_WIKI }} > "modify_repo.json"

        cat modify_repo.json

      shell: bash 

    - name: upload output as devicefarm:ListArtifacts
      uses: actions/upload-artifact@v2
      with:
          name: modify_repo
          path: ./modify_repo.json  

